global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Vector DB Application monitoring
  - job_name: 'vector-db-app'
    static_configs:
      - targets: ['vector-db-app-prod:5000']
    scrape_interval: 10s
    metrics_path: '/metrics'
